/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Types of messages exchanged over WebSocket.
 */
export type MessageType =
  | "signal"
  | "transcript"
  | "text"
  | "update"
  | "input"
  | "channel_notification"
  | "attachment"
  | "conversation_metadata_updated";

/**
 * Base schema for all WebSocket messages.
 */
export interface WebsocketMessage {
  type: MessageType;
  content: string;
  speaker?: string | null;
  is_user: boolean;
  is_final: boolean;
  msg_id?: string | null;
  session_id?: string | null;
  metadata: {
    [k: string]: unknown;
  };
  attachments?: WebsocketAttachment[];
  [k: string]: unknown;
}
/**
 * One assistant-sent media item delivered alongside a chat reply.
 *
 * Only ``image`` kinds are emitted today; the schema is shaped for
 * future audio / document / video without needing another wire-format
 * change. ``url`` is always a path the browser can fetch directly:
 * ``media://`` URIs are rewritten to ``/api/media/<session>/<file>``
 * server-side; ``http(s)://`` URIs pass through unchanged.
 */
export interface WebsocketAttachment {
  kind: string;
  url: string;
  mime_type: string;
  caption: string | null;
  [k: string]: unknown;
}
