#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["PyYAML>=6.0.2,<7"]
# ///
"""Generate Pi and Codex definitions from portable Markdown agents."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tempfile
from pathlib import Path

import yaml
from yaml.nodes import MappingNode, ScalarNode

BANNER = "# Generated by sync_agents.py; do not edit.\n"


def quote(value: str) -> str:
    """JSON string escapes also work in YAML and TOML basic strings."""
    return json.dumps(value, ensure_ascii=False).replace("\x7f", "\\u007f")


def read_agent(source: Path) -> tuple[str, str, str]:
    text = source.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError("missing YAML frontmatter")
    header, separator, body = text[4:].partition("\n---\n")
    if not separator or not body.strip():
        raise ValueError("missing frontmatter closing delimiter or empty body")
    node = yaml.compose(header, Loader=yaml.SafeLoader)
    if not isinstance(node, MappingNode):
        raise ValueError("metadata must be a mapping")
    metadata: dict[str, str] = {}
    for key, value in node.value:
        if (not isinstance(key, ScalarNode) or not isinstance(value, ScalarNode)
                or key.tag != "tag:yaml.org,2002:str" or value.tag != "tag:yaml.org,2002:str"):
            raise ValueError("metadata keys and values must be strings")
        if key.value in metadata:
            raise ValueError(f"duplicate metadata key: {key.value}")
        metadata[key.value] = value.value
    if set(metadata) != {"name", "description"}:
        raise ValueError("metadata must contain exactly name and description")
    name, description = metadata["name"], metadata["description"]
    if not re.fullmatch(r"[a-z][a-z0-9_-]*", name):
        raise ValueError("name must start with a-z and contain only a-z, 0-9, _ or -")
    if not description.strip():
        raise ValueError("description must not be empty")
    return name, description, body


def render(source: Path, root: Path) -> dict[Path, str]:
    name, description, body = read_agent(source)
    fields = {"name": name, "description": description}
    pi = "---\n" + BANNER
    pi += "\n".join(f"{key}: {quote(value)}" for key, value in fields.items())
    pi += "\n---\n" + body
    fields["developer_instructions"] = body
    codex = BANNER + "\n".join(f"{key} = {quote(value)}" for key, value in fields.items()) + "\n"
    return {root / f".pi/agents/{name}.md": pi, root / f".codex/agents/{name}.toml": codex}


def read_target(path: Path, root: Path) -> str | None:
    for component in (path, *path.parents):
        if component == root:
            break
        if component.is_symlink():
            raise ValueError(f"refusing symlink output path: {component}")
        if component != path and component.exists() and not component.is_dir():
            raise ValueError(f"output parent is not a directory: {component}")
    if not path.exists():
        return None
    content = path.read_text(encoding="utf-8")
    prefix = "---\n" + BANNER if path.suffix == ".md" else BANNER
    if not content.startswith(prefix):
        raise ValueError(f"refusing to overwrite a hand-maintained file: {path}")
    return content


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", dir=path.parent, prefix=f".{path.name}.", delete=False,
    )
    staging = Path(temporary.name)
    try:
        with temporary:
            temporary.write(content)
        os.replace(staging, path)
    finally:
        staging.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--source-dir", type=Path, default=Path("agents"),
                        help="source directory, absolute or relative to --root (default: agents)")
    parser.add_argument("--check", action="store_true", help="report drift without writing files")
    args = parser.parse_args()
    root = args.root.resolve()
    source_dir = (root / args.source_dir).resolve()
    for target in (root / ".pi/agents", root / ".codex/agents"):
        if source_dir.is_relative_to(target) or target.is_relative_to(source_dir):
            print(f"agent sync: source/output directories overlap: {source_dir}", file=sys.stderr)
            return 2
    sources = sorted(source_dir.rglob("*.md"))
    if not sources:
        print(f"agent sync: no Markdown definitions found in {source_dir}", file=sys.stderr)
        return 2
    outputs: dict[Path, str] = {}
    for source in sources:
        try:
            generated = render(source, root)
            if outputs.keys() & generated.keys():
                raise ValueError("duplicate agent name")
            outputs.update(generated)
        except (OSError, ValueError, yaml.YAMLError) as exc:
            print(f"agent sync: {source}: {exc}", file=sys.stderr)
            return 2
    try:
        changes = {path: content for path, content in outputs.items()
                   if read_target(path, root) != content}
        if args.check:
            for path in changes:
                print(f"out of sync: {path.relative_to(root)}")
            if not changes:
                print(f"agent sync: {len(sources)} agents, all outputs match")
            return 1 if changes else 0
        for path, content in changes.items():
            write_atomic(path, content)
    except (OSError, ValueError) as exc:
        print(f"agent sync: {exc}", file=sys.stderr)
        return 2
    print(f"agent sync: {len(sources)} agents, wrote {len(changes)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
