[platformio]
default_envs = cores3
src_dir = main
extra_configs = platformio_local.ini

[env]
platform = espressif32@6.9.0
framework = espidf
monitor_speed = 115200
extra_scripts = pre:inject_env.py
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=3

[env:cores3]
board = esp32-s3-devkitc-1
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.psram_type = quad
board_build.partitions = partitions_16MB.csv
build_flags =
    ${env.build_flags}
    -DTARGET_CORES3

[env:pyramid]
board = esp32-s3-devkitc-1
board_build.flash_mode = qio
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.psram_type = quad
board_build.partitions = partitions_8MB.csv
build_flags =
    ${env.build_flags}
    -DTARGET_PYRAMID
