"""Model capability registry sourced from a bundled snapshot.

The snapshot at ``data/models.yaml`` is generated by
``backend/scripts/sync_litellm_models.py`` from LiteLLM's public model
table. Loading it gives Tank knowledge of ~2000+ models' modalities,
context windows, and costs without needing a network call at startup.

Lookup strategy (falls through on miss):
  1. **Exact match** on the configured model id.
  2. **Suffix match** — configured id minus its provider prefix
     (e.g. ``openai/gpt-4o`` → ``gpt-4o``, ``google/gemini-2.5-flash``
     → ``gemini-2.5-flash``). When multiple rows share the same
     suffix, prefer the one that's already unprefixed in the table;
     else the row with the richer modality set.
  3. **No match** — caller falls back to pattern matching or declares
     the model text-only.

The registry is loaded once at module import. It's a pure data
operation; no network, no config dependency.
"""

from __future__ import annotations

import functools
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)

# The bundled yaml ships inside the package.
_DATA_PATH = Path(__file__).parent / "data" / "models.yaml"


@dataclass(frozen=True, slots=True)
class ModelRecord:
    """Projection of one LiteLLM row into the fields Tank cares about."""

    id: str
    provider: str
    modalities: frozenset[str]
    max_input_tokens: int | None = None
    max_output_tokens: int | None = None
    deprecation_date: str | None = None
    flags: frozenset[str] = field(default_factory=frozenset)
    costs: dict[str, float] = field(default_factory=dict)


class ModelRegistry:
    """In-memory lookup table keyed by model id."""

    def __init__(self, records: list[ModelRecord]) -> None:
        self._by_id: dict[str, ModelRecord] = {r.id: r for r in records}
        # Index by the unprefixed suffix (``gpt-4o`` → list of records).
        self._by_suffix: dict[str, list[ModelRecord]] = {}
        for record in records:
            suffix = record.id.rsplit("/", 1)[-1]
            self._by_suffix.setdefault(suffix, []).append(record)

    # ------------------------------------------------------------------
    # Construction
    # ------------------------------------------------------------------

    @classmethod
    def from_yaml(cls, path: Path = _DATA_PATH) -> ModelRegistry:
        """Load the bundled snapshot and build the registry.

        Absent file is treated as empty registry (useful in minimal
        test environments that don't ship the data file).
        """
        if not path.exists():
            logger.warning("Model registry data file missing: %s", path)
            return cls([])

        with path.open("r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}

        rows = data.get("models") or []
        records: list[ModelRecord] = []
        for row in rows:
            if not isinstance(row, dict):
                continue
            try:
                records.append(_record_from_row(row))
            except (KeyError, TypeError, ValueError) as exc:
                logger.debug("Skipping malformed row %r: %s", row.get("id"), exc)
        return cls(records)

    # ------------------------------------------------------------------
    # Lookup
    # ------------------------------------------------------------------

    def lookup(self, model_id: str) -> ModelRecord | None:
        """Return the best matching record, or ``None`` on miss.

        See module docstring for the lookup waterfall.
        """
        if not model_id:
            return None

        # Stage 1 — exact.
        exact = self._by_id.get(model_id)
        if exact is not None:
            return exact

        # Stage 2 — suffix match. When the caller says ``openai/gpt-4o``
        # we want to resolve to ``gpt-4o`` even though the table stores
        # them both; same for ``google/gemini-...`` routing via
        # OpenRouter vs a direct call.
        suffix = model_id.rsplit("/", 1)[-1]
        candidates = self._by_suffix.get(suffix) or []
        if not candidates:
            return None

        return _pick_canonical(candidates)

    # ------------------------------------------------------------------
    # Introspection helpers (tests + future CLI)
    # ------------------------------------------------------------------

    def __len__(self) -> int:
        return len(self._by_id)

    def ids(self) -> list[str]:
        """All model ids — sorted. Intended for debug/CLI listing."""
        return sorted(self._by_id)


# ---------------------------------------------------------------------------
# Row parsing helpers
# ---------------------------------------------------------------------------


def _record_from_row(row: dict[str, Any]) -> ModelRecord:
    """Project a single yaml row into a ModelRecord.

    Raises on missing required fields; the caller swallows and logs.
    """
    model_id = row["id"]
    if not isinstance(model_id, str):
        raise TypeError("id must be a string")

    modalities = row.get("modalities") or ["text"]
    if not isinstance(modalities, list):
        raise TypeError("modalities must be a list")

    flags_list = row.get("flags") or []
    if not isinstance(flags_list, list):
        raise TypeError("flags must be a list")

    costs = row.get("costs") or {}
    if not isinstance(costs, dict):
        raise TypeError("costs must be a dict")

    return ModelRecord(
        id=model_id,
        provider=row.get("provider", ""),
        modalities=frozenset(modalities),
        max_input_tokens=_as_int(row.get("max_input_tokens")),
        max_output_tokens=_as_int(row.get("max_output_tokens")),
        deprecation_date=row.get("deprecation_date"),
        flags=frozenset(flags_list),
        costs={k: float(v) for k, v in costs.items() if isinstance(v, (int, float))},
    )


def _as_int(v: Any) -> int | None:
    """Coerce numeric-ish values to ``int``; treat None and junk as missing."""
    if v is None:
        return None
    try:
        return int(v)
    except (TypeError, ValueError):
        return None


def _pick_canonical(candidates: list[ModelRecord]) -> ModelRecord:
    """Choose the best record when a suffix maps to several rows.

    Priority:
    1. Unprefixed id (``gpt-4o`` beats ``azure/gpt-4o``) — this is the
       row users configuring a direct vendor call would land on.
    2. Richer modality set — if all candidates are prefixed variants,
       pick the one that claims the most input modalities. Ties are
       broken lexically by id so the choice is deterministic.

    We prefer richer over narrower because Tank's capability check is a
    permission gate at upload time; if a variant supports audio we want
    users to be able to send audio, even if a different provider-prefixed
    row of the same family doesn't.
    """
    unprefixed = [r for r in candidates if "/" not in r.id]
    if unprefixed:
        return max(unprefixed, key=lambda r: (len(r.modalities), r.id))
    return max(candidates, key=lambda r: (len(r.modalities), r.id))


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------


@functools.lru_cache(maxsize=1)
def registry() -> ModelRegistry:
    """Return the process-wide registry, loading on first call."""
    return ModelRegistry.from_yaml()


def reset_registry_cache() -> None:
    """Drop the cached registry. Used in tests that swap the data file."""
    registry.cache_clear()
